using JournalApp.Data;
using JournalApp.Data.Repositories;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Text.RegularExpressions;

namespace JournalApp.Services;

public class PdfExportService
{
    private readonly JournalRepository _repo;

    public PdfExportService(JournalRepository repo)
    {
        _repo = repo;
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public async Task<string> ExportAsync(DateTime from, DateTime to)
    {
        var entries = await _repo.GetRangeAsync(from, to);

        var fileName = $"JournalApp_{from:yyyyMMdd}_{to:yyyyMMdd}.pdf";
        var path = Path.Combine(FileSystem.AppDataDirectory, fileName);

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(25);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header()
                    .Text($"Journal Export ({from:yyyy-MM-dd} to {to:yyyy-MM-dd})")
                    .SemiBold().FontSize(16);

                page.Content().Column(col =>
                {
                    if (entries.Count == 0)
                    {
                        col.Item().Text("No entries found in this date range.");
                        return;
                    }

                    foreach (var e in entries.OrderBy(x => x.EntryDate))
                    {
                        col.Item().PaddingBottom(12).BorderBottom(1).BorderColor(QuestPDF.Helpers.Colors.Grey.Lighten2).Column(entryCol =>
                        {
                            entryCol.Item().Text($"{e.EntryDate} — {e.Title}")
                                .SemiBold().FontSize(13);

                            entryCol.Item().Text($"Category: {e.Category}");
                            entryCol.Item().Text($"Mood: {e.PrimaryMood} ({e.PrimaryMoodCategory})");

                            if (!string.IsNullOrWhiteSpace(e.SecondaryMoodsCsv))
                                entryCol.Item().Text($"Secondary: {e.SecondaryMoodsCsv}");

                            if (!string.IsNullOrWhiteSpace(e.TagsCsv))
                                entryCol.Item().Text($"Tags: {e.TagsCsv}");

                            entryCol.Item().Text($"Created: {e.CreatedAt:g} | Updated: {e.UpdatedAt:g} | Words: {e.WordCount}");

                            entryCol.Item().PaddingTop(6).Text(HtmlToPlainText(e.ContentHtml))
                                .FontSize(11);
                        });
                    }
                });

                page.Footer()
                    .AlignCenter()
                    .Text($"Generated by JournalApp • {DateTime.Now:yyyy-MM-dd HH:mm}")
                    .FontSize(9)
                    .FontColor(QuestPDF.Helpers.Colors.Grey.Darken1);
            });
        })
        .GeneratePdf(path);

        return path;
    }

    private static string HtmlToPlainText(string html)
    {
        if (string.IsNullOrWhiteSpace(html)) return "";

        // Remove tags + decode basic spacing
        var text = Regex.Replace(html, "<.*?>", " ");
        text = text.Replace("&nbsp;", " ").Replace("&amp;", "&");
        text = Regex.Replace(text, @"\s+", " ").Trim();

        return text;
    }
}